cake_project_core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("landing_page.urls")),
    path("account/", include("users.urls")),
    path("jobs/", include("jobs.urls")),
    path("courses/", include("courses.urls")),
    # path("accounts/", include("django.contrib.auth.urls")),  # Include Django auth URLs
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        path("favicon.ico", RedirectView.as_view(url="/static/favicon.ico"))
    ]

courses/urls.py
from django.urls import path

from .views import course_detail, course_list, enroll_in_course

app_name = "courses"

urlpatterns = [
    path("", course_list, name="courses_list"),
    path("<int:pk>/", course_detail, name="course_detail"),
    path("<int:pk>/enroll/", enroll_in_course, name="enroll_in_course"),
]

jobs/urls.py
from django.urls import path

from .views import apply_for_job, job_detail, jobs_list_view

app_name = "jobs"

urlpatterns = [
    path("", jobs_list_view, name="jobs_list"),
    path("<int:job_id>/", job_detail, name="job_detail"),
    path("<int:job_id>/apply/", apply_for_job, name="apply_for_job"),
]

users/urls.py
# urls.py
from django.urls import path

from courses.views import course_list
from jobs.views import jobs_list_view

from .views import dashboard, register, user_login, user_logout

app_name = "users"

urlpatterns = [
    path("dashboard/", dashboard, name="dashboard"),
    path("jobs/", jobs_list_view, name="job_list"),
    path("courses/", course_list, name="course_list"),
    path("register/", register, name="register"),
    path("login/", user_login, name="login"),
    path("logout/", user_logout, name="logout"),
]

users/models.py
# models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

# from courses.models import Course
# from jobs.models import Job


class CustomUser(AbstractUser):
    is_decorator = models.BooleanField(default=False)
    is_instructor = models.BooleanField(default=False)
    is_subscriber = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    groups = models.ManyToManyField(
        "auth.Group",
        related_name="customuser_set",  # Change the related name to avoid conflicts
        blank=True,
        help_text="The groups this user belongs to.",
        verbose_name="groups",
    )

    user_permissions = models.ManyToManyField(
        "auth.Permission",
        related_name="customuser_set",  # Change the related name to avoid conflicts
        blank=True,
        help_text="Specific permissions for this user.",
        verbose_name="user permissions",
    )

users/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm

from users.models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ("username", "email", "is_decorator", "is_instructor", "is_subscriber")


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        if user is not None:
            self.user_cache = user
        else:
            raise forms.ValidationError("Invalid username or password.")
        return self.cleaned_data

    def get_user(self):
        return getattr(self, "user_cache", None)

users/views.py
# views.py
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import get_object_or_404, redirect, render

from courses.models import Course, CourseProgress
from jobs.models import Job

from .forms import CustomUserCreationForm, LoginForm


@login_required
def dashboard(request):
    user = request.user
    enrolled_courses = Course.objects.filter(subscribed_users=user)
    course_progresses = CourseProgress.objects.filter(user=user)
    # jobs = Job.objects.filter(subscribed_users=user)
    applied_jobs = Job.objects.filter(applicants=user)

    context = {
        "user": user,
        "enrolled_courses": enrolled_courses,
        "course_progresses": course_progresses,
        "jobs": applied_jobs,
    }

    return render(
        request,
        "users/dashboard.html",
        context,
    )


def register(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            auth_login(request, request.user)  # Log the user in after registration
            # login(request, user)  # Log the user in after registration
            return redirect("courses:courses_list")  # Redirect to a success page
    else:
        form = CustomUserCreationForm()
    return render(request, "users/registration/register.html", {"form": form})


def user_login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("users:dashboard")
    else:
        form = AuthenticationForm()
    return render(request, "users/registration/login.html", {"form": form})


def user_logout(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect("courses:courses_list")
    # return render(request, "users/registration/logout.html")

users/templates/users/dashboard.html
{% extends 'cake_project_core/base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<main class="py-6">
    <section class="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-md mb-6">
        <h1 class="text-3xl font-bold mb-4">Welcome, {{ user.username }}</h1>
        
        <!-- Jobs Section -->
        <div class="mb-6">
            <h2 class="text-2xl font-bold mb-4">Your Jobs</h2>
            <ul id="jobs-list" class="space-y-4">
                {% for job in jobs %}
                    <li class="bg-gray-100 dark:bg-gray-700 p-4 rounded-lg shadow-md flex justify-between items-center">
                        <span class="text-lg font-semibold">{{ job.title }}</span>
                        <a href="{% url 'jobs:job_detail' job.id %}" class="text-blue-500 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-500">View</a>
                    </li>
                {% empty %}
                    <li class="text-gray-700 dark:text-gray-300">No jobs found.</li>
                {% endfor %}
            </ul>
        </div>
        
        <!-- Courses Section -->
        <div>
            <h2 class="text-2xl font-bold mb-4">Your Courses</h2>

            <ul id="courses-list" class="space-y-4">
                {% for progress in enrolled_courses %}
                    <li class="bg-gray-100 dark:bg-gray-700 p-4 rounded-lg shadow-md flex justify-between gap-4 items-center">
                        <div class="flex gap-4 items-center">
                            <img src="{{ progress.get_image_url }}" alt="{{ progress.title }}" class="w-16 h-16 rounded-full mr-4">
                            <span class="text-lg font-semibold">{{ progress.title }}</span>
                        </div>
                        <div class="flex gap-2 justify-end">
                            {% if progress.progress == 100 %}
                                <span class="text-green-500 dark:text-green-400">Completed</span>
                            {% else %}
                                <span class="text-yellow-500 dark:text-yellow-400">In Progress</span>
                            {% endif %}
                            {% if progress.progress %}
                                <span class="text-sm text-gray-600 dark:text-gray-400">{{ progress.progress }}% complete</span>
                            {% endif %}
                            <a href="{% url 'courses:course_detail' pk=progress.id %}" class="text-blue-500 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-500">View</a>
                        </div>
                    </li>
                {% empty %}
                    <li class="text-gray-700 dark:text-gray-300">No courses found.</li>
                {% endfor %}
            </ul>
        </div>
    </section>
</main>
{% endblock content %}